config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'general#index'

  resources :companies, param: :slug do
    resources :jobs, only: [:new, :create, :edit, :show, :update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
# == Schema Information
#
# Table name: companies
#
#  id              :bigint           not null, primary key
#  name            :string
#  location        :string
#  remote_friendly :boolean
#  notes           :string
#  pros            :string
#  cons            :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  slug            :string
#

class Company < ApplicationRecord
  has_many :jobs

  scope :recent_first, -> { order(created_at: :desc) }
  scope :hiring,
        -> { joins(:jobs).where('jobs.company_id > 0') }
  scope :not_hiring,
        -> { left_outer_joins(:jobs).where( jobs: { id: nil } )}
  scope :have_applied, -> { joins(:jobs).merge(Job.have_applied) }
  scope :have_not_applied, -> { where.not(id: have_applied) }

  validates_presence_of :name
  validates_presence_of :location
  validates_uniqueness_of :name

  before_save :update_slug, if: proc { |company| company.name_changed? }

  private

  def update_slug
    self.slug = name.downcase.gsub(' ', '-').gsub(/[,;&!?#]/, '')
  end
end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id               :bigint           not null, primary key
#  company_id       :integer
#  title            :string
#  salary           :string
#  days_remote      :integer
#  where_found      :string
#  notes            :string
#  apply_by         :datetime
#  date_applied     :datetime
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  application_link :string
#

class Job < ApplicationRecord
  belongs_to :company

  validates_presence_of :title

  scope :closing_soon,
        -> { where(apply_by: Time.zone.now..Time.zone.now + 7.days) }
  scope :have_applied, -> { where("date_applied IS NOT NULL") }

  def applied_for?
    !date_applied.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:edit, :show, :update]

  def index
    @applied = Company.have_applied.recent_first
    @not_hiring = Company.not_hiring.recent_first
    @hiring = Company.hiring.have_not_applied.recent_first
  end

  def show
  end

  def new
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to companies_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @company.update(company_params)
    if @company.save
      redirect_to company_path
    else
      render :edit
    end
  end

  private

  def set_company
    @company = Company.find_by(slug: params[:slug])
  end

  def company_params
    params.require(:company).
      permit(:name, :location, :notes, :remote_friendly, :pros, :cons)
  end
end

app/controllers/general_controller.rb
class GeneralController < ApplicationController
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_company
  before_action :set_job, only: [:show, :edit, :update]

  def new
  end

  def create
    @job = Job.new(job_params)
    @job.company_id = @company.id
    if @job.save
      redirect_to company_path(@company.slug)
    else
      render :new
    end
  end

  def show
  end

  def update
    @job.update(job_params)
    @job.company_id = @company.id
    if @job.save
      redirect_to company_job_path(@company.slug, @job.id)
    else
      render :edit
    end
  end

  private

  def job_params
    params.require(:job).
      permit(:title, :salary, :days_remote, :where_found, :apply_by, :notes,
             :date_applied, :application_link)
  end

  def set_company
    @company = Company.find_by(slug: params[:company_slug])
  end

  def set_job
    @job = Job.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/general_helper.rb
module GeneralHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/companies/_form.html.erb
<div class="row">
  <span class="form_label"><%= f.label(:name) %></span>
  <span class="form_data"><%= f.text_field :name %></span>
</div>
<div class="row">
  <span class="form_label"><%= f.label(:location) %></span>
  <span class="form_data"><%= f.text_field :location %></span>
</div>
<div class="row">
  <span class="form_label"><%= f.label(:remote_friendly) %></span>
  <span class="form_data"><%= f.check_box :remote_friendly %></span>
</div>
<div class="row">
  <span class="form_label"><%= f.label(:notes) %></span>
  <span class="form_data"><%= f.text_area(:notes, cols: 80, rows: 10) %><br /></span>
</div>
<div class="row">
  <span class="form_label"><%= f.label(:pros) %></span>
  <span class="form_data"><%= f.text_area(:pros, cols: 80, rows: 5) %><br /></span>
</div>
<div class="row">
  <span class="form_label"><%= f.label(:cons) %></span>
  <span class="form_data"><%= f.text_area(:cons, cols: 80, rows: 5)%><br /></span>
</div>

<%= f.submit %>

app/views/companies/edit.html.erb
<h2>Editing: <%= @company.name %></h2>

<% if @company && @company.errors.any? %>
  <ul class="warning">
    <% @company.errors.each do |attr, message| %>
      <li><%= attr %> <%= message %></li>
    <% end %>
  </ul>
<% end %>

<div id="edit_company">
  <%= form_for :company, url: company_path, method: :patch do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>
  <% end %>
</div>

app/views/companies/index.html.erb
<h2>Who's hiring?</h2>

<ul id="companies">
<% @hiring.each do |company| %>
  <li>
    <%= link_to company.name, company_url(company.slug) %>
    <%- if company.jobs.closing_soon.any? %>
      <span class="warn"><em>Applications closing soon!</em></span>
    <% end %>
  </li>
<% end %>
</ul>

<%-if @not_hiring %>
<h3>No jobs listed</h3>
<ul>
<% @not_hiring.each do |company| %>
<li>
  <%= link_to company.name, company_url(company.slug) %>
</li>
<% end %>
</ul>
<% end %>

<%- if @applied %>
<h3>Application in!</h3>
<ul>
<% @applied.each do |company| %>
  <li>
    <%= link_to company.name, company_url(company.slug) %>
  </li>
<% end %>
<% end %>

</ul>

<%= link_to('Add new', new_company_path) %>

app/views/companies/new.html.erb
<h2>New potential employer</h2>

<% if @company && @company.errors.any? %>
  <ul class="warning">
    <% @company.errors.each do |attr, message| %>
      <li><%= attr %> <%= message %></li>
    <% end %>
  </ul>
<% end %>

<div id="new_company">
  <%= form_for :company, url: companies_path do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>
  <% end %>
</div>

app/views/companies/show.html.erb
<h2><%= @company.name %></h2>

<div id="company_details">
<p>Location: <%= @company.location %></p>

<p>Remote friendly? <%= @company.remote_friendly ? 'Yes' : 'No' %>

<p>Pros:</p>
<div>
<%= sanitize(@company.pros.gsub("\n", "<br>"), tags: %w(br)) %>&nbsp;
</div>

<p>Cons:</p>
<div>
<%= sanitize(@company.cons.gsub("\n", "<br>"), tags: %w(br)) %>&nbsp;
</div>

<p>Notes:</p>
<div>
<%= sanitize(@company.notes.gsub("\n", "<br>"), tags: %w(br)) %>&nbsp;
</div>

<h3>Open positions</h3>
<ul>
<% @company.jobs.each do |job| %>
  <li>
    <%= link_to(job.title, company_job_path(@company.slug, job.id)) %>
    <%- if job.days_remote == 5 %>
    <b>(fully remote)</b>
    <% end %>
    <%- if job.applied_for? %>
      (You have already applied!)
    <% end %>
  </li>
<% end %>
</ul>

<%= link_to("Add open position",
            new_company_job_path(@company.slug)) %>

<p><%= link_to("Edit", edit_company_path(slug: @company.slug)) %></p>

app/views/general/index.html.erb
<div>
  Stuff goes here
</div>

app/views/jobs/_form.html.erb
<div class="row">
  <span class="form_label"><%= f.label(:title) %></span>
  <span class="form_data"><%= f.text_field :title %></span>
</div>
<div class="row">
  <span class="form_label"><%= f.label(:salary) %></span>
  <span class="form_data"><%= f.text_field :salary %></span>
</div>
<div class="row">
  <span class="form_label"><%= f.label(:days_remote) %></span>
  <span class="form_data"><%= f.text_field :days_remote %></span>
</div>
<div class="row">
  <span class="form_label"><%= f.label(:where_found, "Where did you see this advertised?") %></span>
  <span class="form_data"><%= f.text_field :where_found %></span>
</div>
<div class="row">
  <span class="form_label"><%= f.label(:application_link) %></span>
  <span class="form_data"><%= f.text_field :application_link, size: 70 %></span>
</div>
<div class="row">
  <span class="form_label"><%= f.label(:notes) %></span>
  <span class="form_data"><%= f.text_area(:notes, cols: 80, rows: 10) %><br /></span>
</div>
<div class="row">
  <span class="form_label"><%= f.label(:apply_by) %></span>
  <span class="form_data"><%= f.text_field(:apply_by) %><br /></span>
</div>
<div class="row">
  <span class="form_label"><%= f.label(:date_applied) %></span>
  <span class="form_data"><%= f.text_field(:date_applied) %><br /></span>
</div>

<%= f.submit %>

app/views/jobs/edit.html.erb
<h2>Editing role @ <%= @company.name %></h2>

<% if @job && @job.errors.any? %>
  <ul class="warning">
    <% @job.errors.each do |attr, message| %>
      <li><%= attr %> <%= message %></li>
    <% end %>
  </ul>
<% end %>

<div id="edit_job">
  <%= form_for :job, url: company_job_path, method: :patch do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>
  <% end %>
</div>

app/views/jobs/new.html.erb
<h2>New role @ <%= @company.name %></h2>

<% if @job && @job.errors.any? %>
  <ul class="warning">
    <% @job.errors.each do |attr, message| %>
      <li><%= attr %> <%= message %></li>
    <% end %>
  </ul>
<% end %>

<div id="new_job">
  <%= form_for :job, url: company_jobs_path do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>
  <% end %>
</div>

app/views/jobs/show.html.erb
<h2><%= @job.title %> @ <%= @company.name %></h2>

<div id="job_details">
<p>Salary: <%= @job.salary %></p>

<p>Days per week remote: <%= @job.days_remote %></p>

<%- if @job.where_found %>
<p>Found job via <%= @job.where_found %></p>
<% end %>

<%- if @job.applied_for? %>
<p>
  You applied on: <%= @job.date_applied.strftime('%a %d %B') %><br>
  <%- if @job.apply_by %>
  (Applications closed on: <%= @job.apply_by.strftime('%a %d %B') %>)
  <% end %>
</p>
<% else%>
  <%- if @job.application_link %>
    <p><a href="<%= @job.application_link %>">Apply online</a></p>
  <% end %>
  <%- if @job.apply_by %>
    <p>Apply by: <%= @job.apply_by.strftime('%a %d %B') %></p>
  <% end %>
<% end %>

Notes:
<div class="md_notes">
  <%= sanitize(
    Kramdown::Document.new(@job.notes).to_html,
    tags: ['br', 'a', 'b', 'i', 'p', 'ul', 'ol', 'li', 'em', 'strong']) %>
  &nbsp;
</div>
</div>

<p><%= link_to("Edit", edit_company_job_path) %></p>

app/views/layouts/_navigation.html.erb
<%- if controller_name != 'general' %>
  <%= link_to 'Home', root_path %>
  <%- if controller.action_name == 'index' %>
    > <%= controller_name.titlecase %>
  <% else %>
    > <%= link_to 'Companies', companies_path %>
    <%- if controller_name == 'jobs' %>
      > <%= link_to @company.name, company_path(@company.slug) %>
      > <%= @job ? @job.title : 'Adding...' %>
    <% else %>
      > <%= @company ? @company.name : 'Adding...' %>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jobhunter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="nav_bar">
      <%= render partial: 'layouts/navigation' %>
    </div>
    <%= yield %>
  </body>
</html>